import os
import re

# ==========================================
# 設定エリア
# ==========================================

# 1. 出力するファイルパス
OUTPUT_FILE = "js/menu.js"

# 2. スキャンする対象のフォルダと、対応するID
#    "フォルダ名": "ID（js/menu.jsのsubjectSettingsと合わせる）"
TARGET_DIRS = {
    "english": "english",
    "math": "math",
    "kokugo": "kokugo",
    "science": "science",
    "social": "social",
    "info": "info"
}

# 3. 除外するファイル名（必要であれば）
EXCLUDE_FILES = ["template.html", "index.html"]

# ==========================================
# 処理ロジック
# ==========================================

def get_html_title(file_path):
    """HTMLファイルから<title>タグの中身を抽出する"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
            # <title>...</title> を正規表現で探す
            match = re.search(r'<title>(.*?)</title>', content, re.IGNORECASE | re.DOTALL)
            if match:
                return match.group(1).strip()
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
    
    # タイトルが見つからない場合はファイル名を返す
    return os.path.basename(file_path)

def generate_menu_js():
    menu_data = []

    print("--- Scanning directories ---")

    # 設定されたフォルダを順番にスキャン
    for folder, subject_id in TARGET_DIRS.items():
        if not os.path.exists(folder):
            print(f"Skipping missing directory: {folder}")
            continue

        # フォルダ内のファイルを走査
        for filename in os.listdir(folder):
            if filename.endswith(".html") and filename not in EXCLUDE_FILES:
                file_path = os.path.join(folder, filename)
                
                # HTMLのタイトルを取得
                title = get_html_title(file_path)
                
                # パスをWeb用（スラッシュ区切り）に変換 (Windows対策)
                web_path = file_path.replace(os.sep, '/')
                
                print(f"Found: [{subject_id}] {title} ({filename})")
                
                # データに追加
                menu_data.append({
                    "id": subject_id,
                    "title": title,
                    "file": web_path
                })

    # JSファイルの内容を作成
    js_content = f"""/* js/menu.js - Auto-generated by Python */

// 教科ごとの設定 (固定)
const subjectSettings = {{
    english: {{ name: "English", icon: "A", colorClass: "subject-english", description: "単語・長文" }},
    math:    {{ name: "Math",     icon: "∑", colorClass: "subject-math",    description: "数学I・A・II・B" }},
    kokugo:  {{ name: "国語",      icon: "文", colorClass: "subject-kokugo",  description: "現代文・古文・漢文" }},
    science: {{ name: "Science",  icon: "🧪", colorClass: "subject-science", description: "物理・化学・地学" }},
    social:  {{ name: "Social",   icon: "🏛️", colorClass: "subject-social",  description: "歴史・地理" }},
    info:    {{ name: "Info",     icon: "💻", colorClass: "subject-info",    description: "情報・プログラミング" }}
}};

// 自動生成されたページリスト
const menuData = {str(menu_data).replace("'", '"')}; // JSON形式に変換
"""

    # ファイル書き込み
    try:
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(js_content)
        print(f"\nSuccessfully updated {OUTPUT_FILE}!")
    except Exception as e:
        print(f"Error writing file: {e}")

if __name__ == "__main__":
    generate_menu_js()